Результат выполнения Sprint1
Sovinka20/react-burger-1 pull request #1
Opened 2023-06-04 06:20 UTC by Sovinka20

2023-06-04 06:47 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Есть проверка успешности запроса
- Реализовали возможность закрытия модалки по ESC
- Проект соответствует макету
- Использовали `useMemo`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер
- у `IngredientDetails ` нет `propTypes`
- Файл App.test.tsx необходимо удалить - он не понадобится.
- Вы используете атрибут  `style` у тегов, но он должен использоваться только для динамических стилей, во всех остальных случаях должен использоваться класс.
- У модалки в useEffect необходимо вторым параметром передать массив зависимостей, иначе эффект будет срабатывать каждый рендер.
- Компонент App должен быть внутри директории `components/App`.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-06-04 06:47 UTC, andryxxa93 commented on src/components/ingredient-details/ingredientDetails.jsx
> +const IngredientDetails = ({ data }) => {
**Надо исправить**

для этого компонента так же нужно описать PropTypes

2023-06-04 06:47 UTC, andryxxa93 commented on src/App.js
> +  const handlerModelOpen = (model, data) => {
**Можно лучше**
Вот эта функция должна быть внутри `BurgerIngredients ` и `BurgerConstructor `. В будущем сценариев использования модалки станет больше, поэтому хендлеры должны быть для каждого сценария свои.

2023-06-04 06:47 UTC, andryxxa93 commented on src/App.js
> +      e.key === "Escape"
**Можно лучше**
У вас уже есть проверка на уровне модалки была ли нажата клавиша `Escape`. Добавлять её тут повторно не нужно. Так же подобные проверки желательно оставлять на уровне модалки

2023-06-04 10:05 UTC, Sovinka20 commented on src/components/ingredient-details/ingredientDetails.jsx
> +const IngredientDetails = ({ data }) => {
Исправлено.

`IngredientDetails.propTypes = {
  data: PropTypes.object.isRequired,
};`

2023-06-04 10:08 UTC, Sovinka20 commented
Файл App.test.tsx удалён.
Компонент App перемещён в components/app.
Убран style у тегов в AppHeader, BurgerConstructor, BurgerIngredients.
В useEffect вторым параметром передан массив зависимостей, добавлен propTypes для IngredientDetails.
Для "у ModalOverlay не должно быть children" (добавлена ссылка на документацию, где используется children для createPortal).

2023-06-04 20:02 UTC, andryxxa93 commented
**Необходимо исправить**
Сейчас получается, что под `data` может прийти объект любого содержания, но это не так. Необходимо полностью расписать тип ингредиента со всеми его полями (чтобы не дублировать код - сделайте это в отдельном файле) и использовать во всех подобных местах. Вам помогут в этом функции propTypes `arrayOf` и `shape`.

2023-06-04 20:35 UTC, Sovinka20 commented
`IngredientDetails.propTypes = {
  data: ingridientPropType,
};
/*
PropTypes.shape({
  _id: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  type: PropTypes.oneOf(["bun", "sauce", "main"]).isRequired,
  proteins: PropTypes.number.isRequired,
  fat: PropTypes.number.isRequired,
  carbohydrates: PropTypes.number.isRequired,
  calories: PropTypes.number.isRequired,
  price: PropTypes.number.isRequired,
  image: PropTypes.string.isRequired,
  image_mobile: PropTypes.string.isRequired,
  image_large: PropTypes.string.isRequired,
}).isRequired;

https://ru.react.js.org/docs/typechecking-with-proptypes.html

Объект с определённой структорой

optionalObjectWithShape: PropTypes.shape({
    color: PropTypes.string,
    fontSize: PropTypes.number
  }),

*/`

2023-06-05 08:02 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-06-18 13:54 UTC, merged